apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-e2ln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-e2ln
    app.kubernetes.io/part-of: build-suite-test-application-rzfw
  name: devfile-sample-hello-world-e2ln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-e2ln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-e2ln
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-zgyb-tenant/build-suite-test-application-rzfw/devfile-sample-hello-world-e2ln@sha256:902b538529de0df8649c492c0543b555641ce3adf94ce940bc06a0d29a71c94d
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
